services:

  httpd-proxy:
    container_name: httpd-proxy
    build: ./httpd-proxy/
    networks:
      default:
        aliases:
          - ghsamlstack.localhost
    ports:
      - "80:80"
      - "443:443"

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      # LDAP_DOMAIN and LDAP_BASE_DN must match !
      LDAP_DOMAIN: "ghsamlstack.localhost"
      LDAP_BASE_DN: "dc=ghsamlstack,dc=localhost"
      LDAP_ORGANISATION: "GH Saml Stack Organization"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_TLS: "false"             # deactivate TLS for the LDAP server
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      start_period: 50s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./resources/ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    networks:
      - default
    ports:
      - "389"                   # default port for unsecured LDAP
    command: --copy-service --loglevel debug
    restart: unless-stopped

  ldap-phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"   # deactivate HTTPS
    networks:
      - default
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      ldap:
        condition: service_healthy

  gh-saml-sp-shibboleth:
    build:
      context: ./gh-saml-sp-shibboleth/
      dockerfile: Dockerfile
    image: gh/saml-sp-shibboleth:latest
    profiles:
      - builder # Evita que se levante al hacer 'up'

  gh-saml-sp-simplesamlphp:
    build:
      context: ./gh-saml-sp-simplesamlphp/
      dockerfile: Dockerfile
    image: gh/saml-sp-simplesamlphp:latest
    profiles:
      - builder # Evita que se levante al hacer 'up'

  idp-simplesamlphp:
    container_name: idp-simplesamlphp
    build:
      context: ./gh-sp-simplesamlphp/
      dockerfile: Dockerfile
      args:
        - ROLE_SIMPLESAML=idp
    links:
      - httpd-proxy:ghsamlstack.localhost
    networks:
      default:
        aliases:
          - idp.simplesamlphp.ghsamlstack.localhost
    ports:
      - "443"
    secrets:
      - source: sp_simple_cert
      - source: sp_simple_key

  sp-simplesamlphp:
    container_name: sp-simplesamlphp
    build:
      context: ./gh-sp-simplesamlphp/
      dockerfile: Dockerfile
      args:
        - ROLE_SIMPLESAML=sp
    links:
      - httpd-proxy:ghsamlstack.localhost
    networks:
      default:
        aliases:
          - sp.simplesamlphp.ghsamlstack.localhost
    ports:
      - "443"
    secrets:
      - source: sp_simple_cert
      - source: sp_simple_key

  idp-shibboleth:
    container_name: idp-shibboleth
    platform: linux/amd64
    build: ./gh-idp-shibboleth-3.4/
    depends_on:
      ldap:
        condition: service_healthy
    environment:
      - JETTY_MAX_HEAP=128m
      - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
      - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
      - "4443"
    networks:
      default:
        aliases:
          - idp.shibboleth.ghsamlstack.localhost
    secrets:
      - source: idp_backchannel
      - source: idp_browser
      - source: idp_sealer
      - source: idp_encryption_cert
      - source: idp_encryption_key
      - source: idp_signing_cert
      - source: idp_signing_key

  sp-shibboleth:
    container_name: sp-shibboleth
    build:
      context: ./gh-sp-shibboleth/
      dockerfile: Dockerfile
    networks:
      default:
        aliases:
          - sp.shibboleth.ghsamlstack.localhost
    ports:
      - "80"
    secrets:
      - source: sp_shibboleth_cert
      - source: sp_shibboleth_key

  php-cas:
    container_name: php-cas
    extra_hosts:
      - "idp.shibboleth.ghsamlstack.localhost:host-gateway"
    build: ./php-cas/
    links:
      - httpd-proxy:ghsamlstack.localhost
    networks:
      default:
        aliases:
          - cas.ghsamlstack.localhost

networks:
  default:
    name: gh_devel
    driver: bridge

secrets:
  idp_encryption_cert:
    file: ./secrets/idp/idp-encryption-cert.pem
  idp_encryption_key:
    file: ./secrets/idp/idp-encryption-key.pem
  idp_signing_cert:
    file: ./secrets/idp/idp-signing-cert.pem
  idp_signing_key:
    file: ./secrets/idp/idp-signing-key.pem
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_sealer:
    file: ./secrets/idp/sealer.jks

  sp_shibboleth_cert:
    file: ./secrets/sp_shibboleth/sp-certificate.pem
  sp_shibboleth_key:
    file: ./secrets/sp_shibboleth/sp-privatekey.pem

  sp_simple_cert:
    file: ./secrets/sp_simple/sp-certificate.pem
  sp_simple_key:
    file: ./secrets/sp_simple/sp-privatekey.pem
