services:
  httpd-proxy:
    container_name: httpd-proxy
    build: ./httpd-proxy/
    networks:
      - front
      - back
    ports:
      - "80:80"
      - "443:443"

  idp:
    container_name: idp
    platform: linux/amd64
    build: ./gh-idp-shibboleth-3.4/
    depends_on:
      - ldap
    environment:
      - JETTY_MAX_HEAP=128m
      - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
      - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
      - "4443"
    networks:
      - back
    secrets:
      - source: idp_backchannel
      - source: idp_browser
      - source: idp_sealer
      - source: idp_encryption_cert
      - source: idp_encryption_key
      - source: idp_signing_cert
      - source: idp_signing_key

  ldap:
    container_name: ldap
    build: ./ldap/
    networks:
      - back

  gh-saml-sp-shibboleth:
    build:
      context: ./gh-saml-sp-shibboleth/
      dockerfile: Dockerfile
    image: gh/saml-sp-shibboleth:latest
    profiles:
      - builder # Evita que se levante al hacer 'up'

  gh-saml-sp-simplesamlphp:
    build:
      context: ./gh-saml-sp-simplesamlphp/
      dockerfile: Dockerfile
    image: gh/saml-sp-simplesamlphp:latest
    depends_on:
      - gh-saml-sp-shibboleth
    profiles:
      - builder # Evita que se levante al hacer 'up'

  sp:
    container_name: sp
    build:
      context: ./gh-sp-shibboleth/
      dockerfile: Dockerfile
    networks:
      - back
    secrets:
      - source: sp_shibboleth_cert
      - source: sp_shibboleth_key

  simplesamlphp:
    container_name: simplesamlphp
    build:
      context: ./gh-sp-simplesamlphp/
      dockerfile: Dockerfile
    links:
      - httpd-proxy:idptestbed.localhost
    networks:
      - back
    secrets:
      - source: sp_simple_cert
      - source: sp_simple_key

  php-cas:
    container_name: php-cas
    build: ./php-cas/
    links:
      - httpd-proxy:idptestbed.localhost
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_encryption_cert:
    file: ./secrets/idp/idp-encryption-cert.pem
  idp_encryption_key:
    file: ./secrets/idp/idp-encryption-key.pem
  idp_signing_cert:
    file: ./secrets/idp/idp-signing-cert.pem
  idp_signing_key:
    file: ./secrets/idp/idp-signing-key.pem
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_sealer:
    file: ./secrets/idp/sealer.jks

  sp_shibboleth_cert:
    file: ./secrets/sp_shibboleth/sp-certificate.pem
  sp_shibboleth_key:
    file: ./secrets/sp_shibboleth/sp-privatekey.pem

  sp_simple_cert:
    file: ./secrets/sp_simple/sp-certificate.pem
  sp_simple_key:
    file: ./secrets/sp_simple/sp-privatekey.pem
