ServerName https://idp.simplesamlphp.ghsamlstack.localhost:443
UseCanonicalName On

LogLevel info
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Host}i\" \"%{X-Forwarded-For}i\" \"%{User-Agent}i\" \"%{Referer}i\" \"%{Cookie}i\"" ghLogFormat
CustomLog /dev/stdout ghLogFormat
ErrorLog /dev/stderr

<VirtualHost *:443>
    ProxyPreserveHost On
</VirtualHost>