SSLEngine on
SSLCompression off

SSLProtocol all -SSLv2 -SSLv3 -TLSv1
SSLHonorCipherOrder on
SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH EDH+aRSA !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4"

# SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
# SSLHonorCipherOrder on
# SSLCipherSuite HIGH:!aNULL:!MD5:!3DES

SSLCertificateFile    /etc/httpd/ssl/server.cert.pem
SSLCertificateKeyFile /etc/httpd/ssl/server.key.pem
SSLProxyCACertificateFile /etc/httpd/ssl/ca-chain.cert.pem

SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

ProxyPreserveHost on
RequestHeader set X-Forwarded-Proto "https" env=HTTPS
RequestHeader set REMOTE-USER %{REMOTE_USER}s

RequestHeader set X-Forwarded-Port 443

# SSL input filter read failed. -> esto es por certificado que usa el IDP Shibboleth, que no es válido para el hostname del proxy. Se puede ignorar porque el proxy no verifica el certificado del IDP.
KeepAlive Off