SSLEngine on
SSLCompression off

SSLProtocol all -SSLv2 -SSLv3 -TLSv1
SSLHonorCipherOrder on
SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH EDH+aRSA !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4"

SSLCertificateFile    /etc/httpd/ssl/ghsamlstack.localhost.cert.pem
SSLCertificateKeyFile /etc/httpd/ssl/ghsamlstack.localhost.key.pem

SSLProxyEngine on
SSLProxyVerify none
SSLProxyCheckPeerCN off
SSLProxyCheckPeerName off
SSLProxyCheckPeerExpire off

ProxyPreserveHost on
RequestHeader set X-Forwarded-Proto "https" env=HTTPS
RequestHeader set REMOTE-USER %{REMOTE_USER}s