ServerName idptestbed.localhost

<VirtualHost *:80>
    ServerName https://idptestbed.localhost:443
    UseCanonicalName On

    DocumentRoot "/var/www/html"
    DirectoryIndex index.php index.html

    <Location /php-shib-protected>
        AuthType shibboleth

        # Carga la sesión de Shibboleth si existe
        ShibRequestSetting requireSession 1

        ShibRequestSetting applicationId default

        # Requiere un usuario autenticado válido
        Require valid-user
    </Location>
</VirtualHost>
