ServerName idptestbed.localhost

<VirtualHost *:80>
    ServerName https://idptestbed.localhost:443
    UseCanonicalName On

    DocumentRoot "/var/www/html"
    DirectoryIndex index.php index.html

    <Location /php-shib-protected/idp-default>
        AuthType shibboleth

        # Carga la sesión de Shibboleth si existe
        ShibRequestSetting requireSession 1
        # ShibRequestSetting entityID https://secaas-labs-poc-01.org/idp/shibboleth

        # Requiere un usuario autenticado válido
        Require valid-user

        # Solo usuarios con un dominio de correo específico
        # Require shib-attr mail *@tu-universidad.edu

        # Solo miembros de un grupo específico
        # Require shib-attr entitlement urn:mace:example.com:entitlement:admin
    </Location>

    <Location /php-shib-protected/idp-nauthilus-preidp>
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        ShibRequestSetting applicationId nauthilusPreIdP
        Require valid-user
    </Location>
</VirtualHost>
