# ServerName https://sp.shibboleth.ghsamlstack.localhost
# UseCanonicalName On

LogLevel debug mod_shib:trace8
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Host}i\" \"%{X-Forwarded-For}i\" \"%{User-Agent}i\" \"%{Referer}i\" \"%{Cookie}i\"" ghLogFormat
CustomLog /dev/stdout ghLogFormat
ErrorLog /dev/stderr

ServerName sp.shibboleth.ghsamlstack.localhost

<VirtualHost *:80>
    ServerName https://sp.shibboleth.ghsamlstack.localhost:443
    UseCanonicalName On
    ProxyPreserveHost On
    #DocumentRoot "/var/www/html"
    #DirectoryIndex index.php index.html
    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All

        AuthType shibboleth
        ShibRequestSetting requireSession 1
        require shib-session
        # Require valid-user
    </Directory>
    <LocationMatch "^/.*">
        #AuthType shibboleth

        # Carga la sesión de Shibboleth si existe
        #ShibRequestSetting requireSession true
        # ShibRequestSetting applicationId default
        #Require valid-user

        # Requiere un usuario autenticado válido
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        require shib-session
    </LocationMatch>
    <LocationMatch "(.*)">
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        require shib-session
</LocationMatch>
</VirtualHost>