#Rewrite Rules
#Force SSL

RewriteEngine on
ReWriteCond %{SERVER_PORT} !^443$
RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R,L]

LogLevel info
LogLevel ssl:debug
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Host}i\" \"%{X-Forwarded-For}i\" \"%{User-Agent}i\" \"%{Referer}i\" \"%{Cookie}i\"" ghLogFormat
CustomLog /dev/stdout ghLogFormat
ErrorLog /dev/stderr

<VirtualHost *:443>
    ServerName sp.simplesamlphp.ghsamlstack.localhost
    Include conf.d/includes/proxy-common.conf

    ProxyPass / http://sp.simplesamlphp.ghsamlstack.localhost/
    ProxyPassReverse / http://sp.simplesamlphp.ghsamlstack.localhost/
</VirtualHost>

<VirtualHost *:443>
    ServerName idp.simplesamlphp.ghsamlstack.localhost
    Include conf.d/includes/proxy-common.conf

    ProxyPass / http://idp.simplesamlphp.ghsamlstack.localhost/
    ProxyPassReverse / http://idp.simplesamlphp.ghsamlstack.localhost/
</VirtualHost>

<VirtualHost *:443>
    ServerName idp.shibboleth.ghsamlstack.localhost
    Include conf.d/includes/proxy-common.conf

    #Map /idp to Tomcat
    ProxyPass /idp https://idp.shibboleth.ghsamlstack.localhost:4443/idp
    ProxyPassReverse /idp https://idp.shibboleth.ghsamlstack.localhost:4443/idp
</VirtualHost>

<VirtualHost *:443>
    ServerName sp.shibboleth.ghsamlstack.localhost
    Include conf.d/includes/proxy-common.conf

    ProxyPass /Shibboleth.sso http://sp.shibboleth.ghsamlstack.localhost/Shibboleth.sso
    ProxyPassReverse /Shibboleth.sso http://sp.shibboleth.ghsamlstack.localhost/Shibboleth.sso

    ProxyPass /sp-public http://sp.shibboleth.ghsamlstack.localhost/public
    ProxyPass /php-shib-protected http://sp.shibboleth.ghsamlstack.localhost/php-shib-protected
</VirtualHost>

<VirtualHost *:443>
    ServerName cas.ghsamlstack.localhost
    Include conf.d/includes/proxy-common.conf

    #ProxyPass /php-cas http://cas.ghsamlstack.localhost/php-cas
    #ProxyPassReverse /php-cas http://cas.ghsamlstack.localhost/php-cas

    ProxyPass / http://cas.ghsamlstack.localhost/
    ProxyPassReverse / http://cas.ghsamlstack.localhost/
</VirtualHost>