ServerName spidps.shibboleth.ghsamlstack.localhost

LogLevel info
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Host}i\" \"%{X-Forwarded-For}i\" \"%{User-Agent}i\" \"%{Referer}i\" \"%{Cookie}i\"" ghLogFormat
CustomLog /dev/stdout ghLogFormat
ErrorLog /dev/stderr

<VirtualHost *:80>
    ServerName https://spidps.shibboleth.ghsamlstack.localhost:443
    UseCanonicalName On

    DocumentRoot "/var/www/html"
    DirectoryIndex index.php index.html
    <Location /php-shib-protected>
        AuthType shibboleth
        # Carga la sesión de Shibboleth si existe
        ShibRequestSetting requireSession 1
        ShibRequestSetting applicationId default
        # Requiere un usuario autenticado válido
        Require valid-user
    </Location>
</VirtualHost>